---
- name: jenkins playbook
  hosts: all
  become: true
  vars_files:
   - ["vars/{{ ansible_facts['os_family'] }}.yml","vars/defaults.yml"]

  roles:
   - role: geerlingguy.java
   - role: geerlingguy.jenkins
   # this installs packer and ansible on the jenkins server so that you could run ansible & packer from jenkins itself
   # rather than from localhost.
  #  - role: geerlingguy.ansible
   - role: geerlingguy.packer