---
- name: mysql playbook
  hosts: all
  become: true
  vars:
    mysql_packages:
    - mariadb-client
    - mariadb-server
    - python-mysqldb
  vars_files:
   - vars/main.yml
  roles:
   - role: geerlingguy.mysql