---
- name: nginx playbook
  hosts: all
  become: true
  roles:
   - role: nginxinc.nginx
  post_tasks:
   - name: upload website files
     copy: src=./files/website/ dest=/usr/share/nginx/html/ mode=644
   - name: Allow all access to tcp port 80
     ufw:
       rule: allow
       port: 80
       proto: tcp